### PR TITLE
Prefer meta obj

### PR DESCRIPTION
**Pull request by reyawn**
To help prevent pollution of the namespace in koa-joi-router, support properties in the "meta" sub object.

This also bumps dependencies.

@jlai @aheckmann

### CODE REVIEW

**Comment by reyawn** [comment]
I'd like to add support for the "hidden" attribute on the meta object as well (as per suggestion from @jlai)

**Comment by jlai** [comment]
Should update README.md using meta as the recommended way to specify description/hide

**Comment by reyawn** [comment]
Will do

**Comment by reyawn** [comment]
@jason done

**Comment by jlai** [comment]
:+1:

**Comment by reyawn** [comment]
@jlai OK now I think it's good-to-go.

**Pull request merged**
